"""'followers'

Revision ID: 01298b39161b
Revises: 3e9479e3186b
Create Date: 2019-06-29 09:01:54.111723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01298b39161b'
down_revision = '3e9479e3186b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
